flags:
  time-locale-compat:
    old-locale: false
packages:
- ./bookkeeper
- ./bookkeeper-aeson
setup-info:
  ghc:
    windows64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-unknown-mingw32.tar.xz
        content-length: 155652048
    linux64:
      8.0.1.20161117:
        url: http://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
        content-length: 112047972
    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
        content-length: 113379688
extra-deps:
- Glob-0.7.13
- HUnit-1.5.0.0
- QuickCheck-2.8.2
- abstract-deque-0.3
- abstract-par-0.3.3
- aeson-1.0.2.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- blaze-builder-0.4.0.2
- call-stack-0.1.0
- cassava-0.4.5.1
- cereal-0.5.4.0
- code-page-0.1.1
- conduit-1.2.8
- criterion-1.1.4.0
- data-default-class-0.1.2.0
- dlist-0.8.0.2
- doctest-0.11.0
- enclosed-exceptions-1.0.2
- erf-2.0.0.0
- exceptions-0.8.3
- ghc-paths-0.1.0.9
- hashable-1.2.4.0
- hastache-0.6.1
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- ieee754-0.7.9
- js-flot-0.8.3
- js-jquery-3.1.1
- lifted-base-0.2.3.8
- markdown-unlit-0.4.0
- math-functions-0.2.1.0
- mmorph-1.0.9
- monad-control-1.0.1.0
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.5.0
- optparse-applicative-0.13.0.0
- parallel-3.2.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- quickcheck-io-0.1.4
- random-1.1
- resourcet-1.1.8.1
- scientific-0.3.4.9
- semigroups-0.18.2
- setenv-0.1.1.3
- statistics-0.13.3.0
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.5
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.3
- vector-th-unbox-0.2.1.6
- yaml-0.8.21.1
compiler-check: match-exact
resolver: ghc-8.0.1.20161117
