name:                bookkeeper
version:             "0.3"
synopsis:            Anonymous records and overloaded labels
description:         Please see README.md
homepage:            http://github.com/turingjump/bookkeeper#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
copyright:           (c) Julian K. Arni
github:              turingjump/bookkeeper
tested-with:         GHC == 8.0.1
category:            Data Structures, Records
extra-source-files:
  - CHANGELOG.md
  - README.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10
  - mtl == 2.2.*
  - data-default-class
  - constraints == 0.8.*


library:
  source-dirs:      src
  other-modules:    []
  default-extensions: &allExts
    - AutoDeriveTypeable
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveFunctor
    - DeriveGeneric
    - DeriveFoldable
    - DeriveTraversable
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GADTs
    - MultiParamTypeClasses
    - KindSignatures
    - TypeInType
    - OverloadedStrings
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - OverloadedLabels
    - StandaloneDeriving
    - MagicHash

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    default-extensions: *allExts
    dependencies:
      - bookkeeper
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.9
  doctest:
    main:            Doctest.hs
    source-dirs:     test
    default-extensions: *allExts
    dependencies:
      - doctest >= 0.9 && < 0.12
      - Glob >= 0.7 && < 0.8
      - yaml == 0.8.*

benchmarks:
  bench:
    main:            Main.hs
    source-dirs:     bench
    default-extensions: *allExts
    dependencies:
      - bookkeeper
      - criterion
      - ghc-prim
    ghc-options:     -O3


executables:
  readme:
    main:                Readme.lhs
    ghc-options:         -pgmL markdown-unlit -fno-warn-unused-top-binds
    source-dirs:         exec
    default-extensions:  []
    other-modules:       []
    dependencies:        base >=4.9 && < 4.10
                       , bookkeeper
                       , markdown-unlit
  compileTime:
    main:                CompileTime.hs
    ghc-options:         -Wall
    source-dirs:         exec
    default-extensions: *allExts
    other-modules:       []
    dependencies:        base >=4.9 && < 4.10
                       , bookkeeper
