name:                bookkeeper-aeson
version:             0.1.0.0
synopsis:            Aeson instances for bookkeeper
description:         >
    This package provides ToJSON and FromJSON instances for bookkeeper's
    @Book@ type.
homepage:            http://github.com/turingjump/bookkeeper#readme
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
copyright:           (c) Julian K. Arni
github:              jkarni/bookkeeper-aeson
tested-with:         GHC == 8.0.2

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10
  - aeson
  - bookkeeper
  - text

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - OverloadedLabels
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators
  - MagicHash

library:
  source-dirs:      src
  other-modules:    []

tests:
  spec:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - bookkeeper-aeson
      - hspec > 2 && < 3
      - QuickCheck >= 2.8 && < 2.10
  doctest:
    main:            Doctest.hs
    source-dirs:     test
    dependencies:
      - doctest >= 0.9 && < 0.12
      - Glob >= 0.7 && < 0.8
      - yaml == 0.8.*
